### ISSUE TITLE
PayPal instant checkout bugs

### ISSUE THREAD

**Issue by gingerling** [thirtybees/paypal#28] opened 2020-06-05 16:33 UTC
Hi, I have found a lot of bugs with paypal instant checkout that I'm struggling to reproduce/understand. I have figured out and reported one bug (with the addresses) but had no reply here. Recently, I have had customers complain that they follow the instant checkout process and it seems like it's worked but then they come back to the store and there is no order placed and they get dropped back at the cart page. I have other issues where we get payments via PayPal but the TB side is still a cart and I have to manually make the order.

I have ended up disabling this instant checkout feature. 

Is anyone actively working on this plugin? It seems pretty essential to the store, I use it myself a lot when shopping online. 

I would like to make a bug report for each issue but I don't understand it enough and I can't afford to spend anymore on devs for this (I've probably spent £1000 on support for paypal and stripe over the year and got nowhere with resolving the issues). Can anyone help please?

**Comment by getdatakick** [comment] 2021-03-09 13:53
Closing this issue because it is not specific at all. 

@gingerling if you find any bug, please write down repro-steps. The more details you provide, the bigger chance for us to reproduce and fix the issue.

**Closed by getdatakick** 2021-03-09 13:53 UTC
